### ISSUE TITLE
Ooops, we could not display the DMN table - Cannot read property 'group' of undefined

### ISSUE THREAD

**Issue by jonashackt** [bpmn-io/dmn-js-examples#1]
I followed the setup-steps decribed [here](https://github.com/dmn-io/dmn-js#building-the-project) & [at dmn-js readme](https://github.com/dmn-io/dmn-js/blob/master/docs/project/SETUP.md)  
- git clones of 5 projects
- linking within node_modules folders
- running node install
- and finally a successful grunt

Then i (npm) linked dmn-js to modelers node_modules and did a
- npm install
- and grunt auto-build (see https://github.com/dmn-io/dmn-js-examples/tree/master/modeler#building)

The modeler starts successfully and i can access it via http://localhost:9013/. But when i try to drag a DMN-file (took some of [them](https://github.com/camunda/camunda-engine-dmn/tree/master/engine/src/test/resources/org/camunda/dmn/engine)) or click on "create a new table", i get

Ooops, we could not display the DMN table.
cause of the problem
Cannot read property 'group' of undefined

Any suggestions? Maybe some [bootstrap](http://stackoverflow.com/questions/27620475/bootstrapvalidator-gives-cannot-read-property-group-of-undefined-on-ckeditor) stuff?

**Comment by SebastianStamm** [comment]
Hi,

thanks for reporting. Currently, there is an additional dependency to https://github.com/bpmn-io/diagram-js, which you also have to clone and link.

See the setup script for details: https://github.com/dmn-io/dmn-js/blob/master/docs/project/setup.sh

I will update the setup documentation accordingly.

**Comment by jonashackt** [comment]
Thx, it´s working fine :)
