### ISSUE TITLE
Examples don't work because of new version of dmn-js

### ISSUE THREAD

**Issue by GyGaByyyTe** [bpmn-io/dmn-js-examples#10]

**Comment by pinussilvestrus** [comment]
Hi @GyGaByyyTe ,

can you state out _which examples_ are not working anymore and _what_ is not working there?

**Comment by GyGaByyyTe** [comment]
Hi, @pinussilvestrus !
So, i've just tried the [modeler](https://github.com/bpmn-io/dmn-js-examples/tree/master/modeler)  example on that link ([Try it out](https://cdn.staticaly.com/gh/bpmn-io/dmn-js-examples/master/modeler/modeler.html)), there i got a visually empty page with error in Chrome Dev-Tools console: 
<img width="718" alt="Снимок экрана 2020-02-04 в 16 47 53" src="https://user-images.githubusercontent.com/16051548/73750776-d98b9680-476e-11ea-8777-641cd6e608cc.png">

P.S. viewer also doesn't work properly :(

**Comment by philippfromme** [comment]
I've reverted the last changes that broke the examples. They should be working again.

Related to https://github.com/bpmn-io/dmn-js/issues/459
