### ISSUE TITLE
Hyperlinks in starter return error 400

### ISSUE THREAD

**Issue by VadeveSi** [bpmn-io/dmn-js-examples#15]
__Describe the Bug__

Hi, I was looking around at the examples and I noticed that the links on the [starter examples page](https://github.com/bpmn-io/dmn-js-examples/tree/master/starter) return the following error: `400 Bad Request. The user is not registered with the HTML service. To enable the service please contact https://twitter.com/staticallyio`

__Steps to Reproduce__

Go to the webpage, click on one of the links.

__Environment__

- This happened on the latest Firefox.

**Comment by nikku** [comment]
Seems like we need to ask our CDN to whitelist HTML serving, cf. https://twitter.com/nrehwaldt/status/1265242234926108673.

**Comment by VadeveSi** [comment]
Hi nikku, I just found the issue.

When looking through the examples, I noticed that the statically example of [the modeler](https://github.com/bpmn-io/dmn-js-examples/tree/master/modeler) does work.

Per example, here is one of the urls of the starter example, and the url of the above page.
- https:// cdn.staticaly.com/gh/**dmn-io**/dmn-js-examples/master/starter/modeler.html
- https:// cdn.staticaly.com/gh/**bpmn-io**/dmn-js-examples/master/modeler/modeler.html

It seems like the link is simply wrong. If I change dmn-io to bpmn-io, it works. (https://cdn.staticaly.com/gh/bpmn-io/dmn-js-examples/master/starter/modeler.html)

I haven't found any other broken links, so updating the two links on the starter examples page should fix the issue.

**Comment by nikku** [comment]
Thanks! Fixed via https://github.com/bpmn-io/dmn-js-examples/commit/8ce13d045b08c1f38ed7fc03ce682c5f7414aad2 then.
