### ISSUE TITLE
modeler example doesnt work with dmn-js 9

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/dmn-js-examples#16]
__Describe the Bug__

The dmn-js modeler examples doesnt run correctly with dmn-js@9.0.0 (see below).

__Steps to Reproduce__

Checkout the [modeler example ](https://github.com/bpmn-io/dmn-js-examples/tree/master/modeler) and open the modeler.html page.

![Screenshot_20200727_154344](https://user-images.githubusercontent.com/42800119/88548906-f8812c00-d01f-11ea-980d-93a3995b3eeb.png)

I also tested v8.3.1 and with that version everything runs as expected.

__Expected Behavior__

The panel on the left side is loaded, the drill-downs are working, editing is possible, no errors in console.

__Environment__

- Host (Browser/Node version), if applicable: Arch Linux, Chromium 83
- Library version: See above.

**Comment by scarabaeus** [comment]
Looks like you didn't include the CSS files.
