### ISSUE TITLE
Bundling example is incorrectly updated

### ISSUE THREAD

**Issue by barmac** [bpmn-io/dmn-js-examples#18]
__Describe the Bug__

The automatic update of dmn-js within bundling example is applied only to `package.json` which makes `npm ci` impossible due to version missmatch with `package-lock.json`.

E.g. https://github.com/bpmn-io/dmn-js-examples/commit/4629ba3430002fd01d8c4ff237b4669ac3290d0a
Notice how package.json is updated but package-lock.json stays intact.

__Steps to Reproduce__

Compare current version and version in `package-lock.json`: https://github.com/bpmn-io/dmn-js-examples/blob/master/bundling/package-lock.json#L1204

__Expected Behavior__

Both files are updated accordingly.

**Comment by philippfromme** [comment]
Any hint where to fix this?

**Comment by barmac** [comment]
I believe it should be done here: https://github.com/bpmn-io/dmn-js/blob/develop/tasks/stages/update-examples

**Comment by barmac** [comment]
This will be fixed via https://github.com/bpmn-io/dmn-js/pull/598.

**Comment by barmac** [comment]
Fixed via https://github.com/bpmn-io/dmn-js/pull/598
