### ISSUE TITLE
The simple-bower example produces read only table. 

### ISSUE THREAD

**Issue by mikhailChibel** [bpmn-io/dmn-js-examples#4]
Hi  there, 

I'm playing with simple-bower example and managed to run and see dmn table editor, however, the table is in readonly mode. I can switch between hide/show details and  open script popup dialog, but cannot edit anything.

**Comment by SebastianStamm** [comment]
The `dmn-viewer.js` from the bower distribution is the readonly viewer from dmn-js. If you replace it with `dmn-modeler.js`, you should be able to make changes to the table.
